_target_: dpnlp_lib.src.dp_sgd.DPSGDFedAvg
fraction_fit: 0.5
fraction_evaluate: 0.5
min_fit_clients: 2
min_evaluate_clients: 2
min_available_clients: 2

model_config:
  input_dim: 300
  hidden_dim: 128
  num_layers: 6
  dropout: 0.0 # Generally speaking, differentially private training is enough of a regularizer by itself. Adding any more regularization (such as dropouts or data augmentation) is unnecessary and typically hurts performance. https://opacus.ai/tutorials/building_image_classifier#Tips-and-Tricks

# client side training hyperparameters
fit_config:
  lr: 0.01
  epochs: 1
  noise_multiplier: 1.0
  max_grad_norm: 0.1
