_target_: dpnlp_lib.src.dp_sgd.DPSGDFedAvg
fraction_fit: 0.5
fraction_evaluate: 0.5
min_fit_clients: 2
min_evaluate_clients: 2
min_available_clients: 2

model_config:
  input_dim: 300
  hidden_dim: 128
  num_layers: 6
  dropout: 0.3

# client side training hyperparameters
fit_config:
  lr: 0.01
  epochs: 1
  noise_multiplier: 1.0
  max_grad_norm: 0.1