seed: 42
device: cuda

model:
  model_name: "gpt2"
  tokenizer_name: "gpt2"
  model_revision: "main"
  use_auth_token: false
  sequence_len: 128

data:
  dataset_name: "reddit"
  dataset_split: "train[:500000]"
  test_split_ratio: 0.02
  text_field: "summary"
  prompt: "Summarize the following discharge note:"
  num_proc: 8

train:
  per_device_train_batch_size: 2
  max_steps: 100
  learning_rate: 2e-4
  fp16: false
  bf16: false
  logging_steps: 10
  optim: "adamw_torch"
  weight_decay: 0.01
  lr_scheduler_type: "linear"
  output_dir: "outputs"
  report_to: "none"
  local_rank: 0

privacy:
  target_epsilon: 2.5
  target_delta: 1e-5
  dp_grad_clip: 1.0
  dp_noise_multiplier: 1.0

lora:
  enable_lora: false
  lora_dim: 8
  lora_alpha: 8
  lora_dropout: 0.0